use serde::{Deserialize, Serialize};

use crate::{MoeError, Result};

pub const OLMOE_PUBLIC_ORACLE_SCHEMA: &str = "a3s.moe.olmoe-public-oracle.v1";
pub const OLMOE_PUBLIC_MODEL_ID: &str = "allenai/OLMoE-1B-7B-0924";
pub const OLMOE_PUBLIC_MODEL_REVISION: &str = "6d84c48581ece794365f2b8e9cfb043c68ade9c5";
pub const OLMOE_TRANSFORMERS_REVISION: &str = "918dbf131d0df5b46e3f6e1d96174d62aa4d16d6";
pub const OLMOE_TRANSFORMERS_SOURCE_SHA256: &str =
    "53a94a479f9904674a5f45aba0387c13466a1f2a2d3cdb9226f9cf58946ebbf8";

/// One integrity-bound file used to construct the independent oracle.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct OlmoeOracleFile {
    pub name: String,
    pub bytes: u64,
    pub sha256: String,
}

/// Provenance for the exact model and independent Transformers equations.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct OlmoeOracleModel {
    pub id: String,
    pub revision: String,
    pub transformers_revision: String,
    pub transformers_source_sha256: String,
    pub files: Vec<OlmoeOracleFile>,
}

/// Tokenizer input captured by the independent oracle.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct OlmoeOracleInput {
    pub text: String,
    pub add_special_tokens: bool,
    pub token_ids: Vec<u32>,
}

/// One selected expert and its full-softmax routing probability.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct OlmoeOracleRoute {
    pub expert: u32,
    pub weight: f32,
}

/// Complete prompt logits, router logits, and selected routes.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct OlmoeOracleOutput {
    pub logits: Vec<Vec<f32>>,
    pub layer_router_logits: Vec<Vec<Vec<f32>>>,
    pub layer_routes: Vec<Vec<Vec<OlmoeOracleRoute>>>,
}

/// Versioned, self-contained numerical oracle generated by pinned Transformers.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct OlmoePublicOracle {
    pub schema: String,
    pub model: OlmoeOracleModel,
    pub input: OlmoeOracleInput,
    pub output: OlmoeOracleOutput,
}

/// Absolute tolerances applied independently to each numerical surface.
#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct OlmoeValidationTolerances {
    pub logits_abs: f32,
    pub router_logits_abs: f32,
    pub route_weights_abs: f32,
}

impl Default for OlmoeValidationTolerances {
    fn default() -> Self {
        Self {
            logits_abs: 2e-2,
            router_logits_abs: 2e-2,
            route_weights_abs: 2e-4,
        }
    }
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct OlmoeNumericComparison {
    pub tolerance: f32,
    pub max_abs_diff: f32,
    pub mismatch_count: u64,
}

impl OlmoeNumericComparison {
    pub(super) fn new(tolerance: f32) -> Self {
        Self {
            tolerance,
            max_abs_diff: 0.0,
            mismatch_count: 0,
        }
    }

    pub(super) fn observe(&mut self, actual: f32, expected: f32) -> Result<()> {
        if !actual.is_finite() || !expected.is_finite() {
            return Err(MoeError::InvalidTensor(
                "oracle comparison encountered a non-finite value".to_string(),
            ));
        }
        let difference = (actual - expected).abs();
        let difference = if difference.is_finite() {
            difference
        } else {
            f32::MAX
        };
        self.max_abs_diff = self.max_abs_diff.max(difference);
        if difference > self.tolerance {
            self.mismatch_count = self.mismatch_count.saturating_add(1);
        }
        Ok(())
    }
}

/// Machine-readable result from one full public-checkpoint validation.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum OlmoeValidationStatus {
    Passed,
    Failed,
}

/// Evidence emitted after comparing every captured numerical value.
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct OlmoeValidationReport {
    pub schema: &'static str,
    pub model_id: String,
    pub model_revision: String,
    pub prompt_tokens: usize,
    pub vocabulary_size: usize,
    pub layers: usize,
    pub experts: usize,
    pub routes_checked: u64,
    pub logits: OlmoeNumericComparison,
    pub router_logits: OlmoeNumericComparison,
    pub route_weights: OlmoeNumericComparison,
    pub route_expert_mismatches: u64,
    pub argmax_token_mismatches: u64,
    pub status: OlmoeValidationStatus,
}
