use serde::{Deserialize, Serialize};

pub use crate::validation::{
    NumericComparison as OlmoeNumericComparison, OracleFile as OlmoeOracleFile,
    OracleInput as OlmoeOracleInput, OracleRoute as OlmoeOracleRoute,
    ValidationStatus as OlmoeValidationStatus,
};

pub const OLMOE_PUBLIC_ORACLE_SCHEMA: &str = "a3s.moe.olmoe-public-oracle.v1";
pub const OLMOE_PUBLIC_MODEL_ID: &str = "allenai/OLMoE-1B-7B-0924";
pub const OLMOE_PUBLIC_MODEL_REVISION: &str = "6d84c48581ece794365f2b8e9cfb043c68ade9c5";
pub const OLMOE_TRANSFORMERS_REVISION: &str = "918dbf131d0df5b46e3f6e1d96174d62aa4d16d6";
pub const OLMOE_TRANSFORMERS_SOURCE_SHA256: &str =
    "53a94a479f9904674a5f45aba0387c13466a1f2a2d3cdb9226f9cf58946ebbf8";

/// Provenance for the exact model and independent Transformers equations.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct OlmoeOracleModel {
    pub id: String,
    pub revision: String,
    pub transformers_revision: String,
    pub transformers_source_sha256: String,
    pub files: Vec<OlmoeOracleFile>,
}

/// Complete prompt logits, router logits, and selected routes.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct OlmoeOracleOutput {
    pub logits: Vec<Vec<f32>>,
    pub layer_router_logits: Vec<Vec<Vec<f32>>>,
    pub layer_routes: Vec<Vec<Vec<OlmoeOracleRoute>>>,
}

/// Versioned, self-contained numerical oracle generated by pinned Transformers.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct OlmoePublicOracle {
    pub schema: String,
    pub model: OlmoeOracleModel,
    pub input: OlmoeOracleInput,
    pub output: OlmoeOracleOutput,
}

/// Absolute tolerances applied independently to each numerical surface.
#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct OlmoeValidationTolerances {
    pub logits_abs: f32,
    pub router_logits_abs: f32,
    pub route_weights_abs: f32,
}

impl Default for OlmoeValidationTolerances {
    fn default() -> Self {
        Self {
            logits_abs: 2e-2,
            router_logits_abs: 2e-2,
            route_weights_abs: 2e-4,
        }
    }
}

/// Evidence emitted after comparing every captured numerical value.
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct OlmoeValidationReport {
    pub schema: &'static str,
    pub model_id: String,
    pub model_revision: String,
    pub prompt_tokens: usize,
    pub vocabulary_size: usize,
    pub layers: usize,
    pub experts: usize,
    pub routes_checked: u64,
    pub logits: OlmoeNumericComparison,
    pub router_logits: OlmoeNumericComparison,
    pub route_weights: OlmoeNumericComparison,
    pub route_expert_mismatches: u64,
    pub argmax_token_mismatches: u64,
    pub status: OlmoeValidationStatus,
}
