use a3s_power::inference::{DevicePreference, RuntimeDeviceIdentity};
use serde::{Deserialize, Serialize};

pub use crate::validation::{
    NumericComparison as Qwen36MoeNumericComparison, OracleFile as Qwen36MoeOracleFile,
    OracleInput as Qwen36MoeOracleInput, OracleRoute as Qwen36MoeOracleRoute,
    ValidationStatus as Qwen36MoeValidationStatus,
};

pub const QWEN36_MOE_PUBLIC_ORACLE_SCHEMA: &str = "a3s.moe.qwen3.6-35b-a3b-public-oracle.v1";
pub const QWEN36_MOE_VALIDATION_SCHEMA: &str = "a3s.moe.qwen3.6-35b-a3b-validation.v2";
pub const QWEN36_MOE_PUBLIC_MODEL_ID: &str = "Qwen/Qwen3.6-35B-A3B";
pub const QWEN36_MOE_PUBLIC_MODEL_REVISION: &str = "995ad96eacd98c81ed38be0c5b274b04031597b0";
pub const QWEN36_MOE_TRANSFORMERS_REVISION: &str = "918dbf131d0df5b46e3f6e1d96174d62aa4d16d6";
pub const QWEN36_MOE_TRANSFORMERS_SOURCE_SHA256: &str =
    "16ef7b0dc6e26eae26a6ffd0ad11d93f85424f90ffb85fbcc9eecc0759cc930d";
pub const QWEN36_MOE_TRANSFORMERS_DTYPE: &str = "float32";

/// Provenance for the exact public model and independent equations.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct Qwen36MoeOracleModel {
    pub id: String,
    pub revision: String,
    pub transformers_revision: String,
    pub transformers_source_sha256: String,
    pub transformers_dtype: String,
    pub files: Vec<Qwen36MoeOracleFile>,
}

/// Complete prompt logits and routing surfaces for every text layer.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct Qwen36MoeOracleOutput {
    pub logits: Vec<Vec<f32>>,
    pub layer_router_logits: Vec<Vec<Vec<f32>>>,
    pub layer_routes: Vec<Vec<Vec<Qwen36MoeOracleRoute>>>,
}

/// Versioned public Qwen3.6-35B-A3B oracle generated by pinned Transformers.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct Qwen36MoePublicOracle {
    pub schema: String,
    pub model: Qwen36MoeOracleModel,
    pub input: Qwen36MoeOracleInput,
    pub output: Qwen36MoeOracleOutput,
}

/// Absolute tolerances for independent Transformers F32 versus Candle F32.
#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct Qwen36MoeValidationTolerances {
    pub logits_abs: f32,
    pub router_logits_abs: f32,
    pub route_weights_abs: f32,
}

impl Default for Qwen36MoeValidationTolerances {
    fn default() -> Self {
        Self {
            logits_abs: 2.5e-1,
            router_logits_abs: 1.0e-1,
            route_weights_abs: 5.0e-3,
        }
    }
}

/// Evidence emitted after comparing every captured numerical value.
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct Qwen36MoeValidationReport {
    pub schema: &'static str,
    pub moe_revision: &'static str,
    pub power_revision: &'static str,
    pub requested_device: DevicePreference,
    pub resolved_device: RuntimeDeviceIdentity,
    pub automatic_cpu_fallback: bool,
    pub host_cache_bytes: u64,
    pub device_cache_bytes: u64,
    pub model_id: String,
    pub model_revision: String,
    pub source_weights_sha256: String,
    pub packed_weights_sha256: String,
    pub prompt_tokens: usize,
    pub vocabulary_size: usize,
    pub layers: usize,
    pub linear_attention_layers: usize,
    pub full_attention_layers: usize,
    pub experts: usize,
    pub routes_checked: u64,
    pub logits: Qwen36MoeNumericComparison,
    pub router_logits: Qwen36MoeNumericComparison,
    pub route_weights: Qwen36MoeNumericComparison,
    /// Selected experts absent from the oracle top-k set.
    pub route_expert_mismatches: u64,
    /// Rank changes within an otherwise unordered top-k expert set.
    pub route_order_mismatches: u64,
    pub argmax_token_mismatches: u64,
    pub status: Qwen36MoeValidationStatus,
}
