use serde::{Deserialize, Serialize};

pub use crate::validation::{
    NumericComparison as Qwen3MoeNumericComparison, OracleFile as Qwen3MoeOracleFile,
    OracleInput as Qwen3MoeOracleInput, OracleRoute as Qwen3MoeOracleRoute,
    ValidationStatus as Qwen3MoeValidationStatus,
};

pub const QWEN3_MOE_PUBLIC_ORACLE_SCHEMA: &str = "a3s.moe.qwen3-moe-public-oracle.v1";
pub const QWEN3_MOE_VALIDATION_SCHEMA: &str = "a3s.moe.qwen3-moe-validation.v1";
pub const QWEN3_MOE_PUBLIC_MODEL_ID: &str = "Qwen/Qwen3-30B-A3B-Base";
pub const QWEN3_MOE_PUBLIC_MODEL_REVISION: &str = "1b75feb79f60b8dc6c5bc769a898c206a1c6a4f9";
pub const QWEN3_MOE_TRANSFORMERS_REVISION: &str = "918dbf131d0df5b46e3f6e1d96174d62aa4d16d6";
pub const QWEN3_MOE_TRANSFORMERS_SOURCE_SHA256: &str =
    "56d820671d810b68f31056605cec0c674994c8f962370194225911ac6a71a365";
pub const QWEN3_MOE_TRANSFORMERS_DTYPE: &str = "bfloat16";

/// Provenance for the exact public model and independent equations.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct Qwen3MoeOracleModel {
    pub id: String,
    pub revision: String,
    pub transformers_revision: String,
    pub transformers_source_sha256: String,
    pub transformers_dtype: String,
    pub files: Vec<Qwen3MoeOracleFile>,
}

/// Complete prompt logits and optional router surfaces for every layer.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct Qwen3MoeOracleOutput {
    pub logits: Vec<Vec<f32>>,
    pub layer_router_logits: Vec<Option<Vec<Vec<f32>>>>,
    pub layer_routes: Vec<Option<Vec<Vec<Qwen3MoeOracleRoute>>>>,
}

/// Versioned public Qwen3-MoE oracle generated by pinned Transformers.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct Qwen3MoePublicOracle {
    pub schema: String,
    pub model: Qwen3MoeOracleModel,
    pub input: Qwen3MoeOracleInput,
    pub output: Qwen3MoeOracleOutput,
}

/// Absolute tolerances for a BF16 Transformers oracle versus F32 execution.
#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct Qwen3MoeValidationTolerances {
    pub logits_abs: f32,
    pub router_logits_abs: f32,
    pub route_weights_abs: f32,
}

impl Default for Qwen3MoeValidationTolerances {
    fn default() -> Self {
        Self {
            logits_abs: 2.5e-1,
            router_logits_abs: 1.0e-1,
            route_weights_abs: 5.0e-3,
        }
    }
}

/// Evidence emitted after comparing every captured numerical value.
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct Qwen3MoeValidationReport {
    pub schema: &'static str,
    pub model_id: String,
    pub model_revision: String,
    pub source_weights_sha256: String,
    pub packed_weights_sha256: String,
    pub prompt_tokens: usize,
    pub vocabulary_size: usize,
    pub layers: usize,
    pub sparse_layers: usize,
    pub experts: usize,
    pub routes_checked: u64,
    pub logits: Qwen3MoeNumericComparison,
    pub router_logits: Qwen3MoeNumericComparison,
    pub route_weights: Qwen3MoeNumericComparison,
    pub route_expert_mismatches: u64,
    pub argmax_token_mismatches: u64,
    pub status: Qwen3MoeValidationStatus,
}
